//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestKeyCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int IdVenta { get; set; }
        public int VendedoresIdVendedor { get; set; }
        public int ProductosIdProducto { get; set; }
        public System.DateTime Dt_FechaVenta { get; set; }
        public int Nu_Cantidad { get; set; }
    
        public virtual Vendedores Vendedores { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
